#!/usr/bin/env bash
# Configuration management for NQRust-MicroVM installer
# Generates configuration files and sets up system user

# Create system user
create_system_user() {
    log_info "Creating system user..."

    if id "nqrust" >/dev/null 2>&1; then
        log_info "User 'nqrust' already exists"
    else
        sudo useradd --system --no-create-home --shell /usr/sbin/nologin nqrust
        log_success "Created system user 'nqrust'"
    fi

    # Add to kvm group
    sudo usermod -a -G kvm nqrust

    # Add to docker group if docker is installed (for container feature)
    if getent group docker >/dev/null 2>&1; then
        sudo usermod -a -G docker nqrust
        log_info "Added nqrust to docker group"
    fi

    log_success "System user configured"
}

# Create directory structure
create_directory_structure() {
    log_info "Creating directory structure..."

    # Installation directory
    create_dir "${INSTALL_DIR}" "root:root" "755"
    create_dir "${INSTALL_DIR}/bin" "root:root" "755"
    create_dir "${INSTALL_DIR}/scripts" "root:root" "755"
    create_dir "${INSTALL_DIR}/backups" "nqrust:nqrust" "750"

    # Configuration directory
    create_dir "${CONFIG_DIR}" "root:root" "755"

    # Data directories
    create_dir "${DATA_DIR}" "nqrust:nqrust" "755"
    create_dir "${DATA_DIR}/vms" "nqrust:nqrust" "755"
    create_dir "${IMAGE_DIR}" "nqrust:nqrust" "755"

    # Log directory
    create_dir "/var/log/nqrust-microvm" "nqrust:nqrust" "755"

    # UI directory (if installing UI)
    if [[ "${WITH_UI:-true}" == "true" ]]; then
        create_dir "${INSTALL_DIR}/ui" "nqrust:nqrust" "755"
    fi

    log_success "Directory structure created"
}

# Generate manager configuration
generate_manager_config() {
    log_info "Generating manager configuration..."

    local config_file="${CONFIG_DIR}/manager.env"

    cat <<EOF | sudo tee "$config_file" >/dev/null
# NQRust-MicroVM Manager Configuration
# Generated by installer on $(date)

# Database connection
DATABASE_URL=${DB_CONNECTION_STRING}

# Manager bind address
MANAGER_BIND=${MANAGER_BIND:-0.0.0.0:18080}

# Storage paths
MANAGER_IMAGE_ROOT=${IMAGE_DIR}
MANAGER_STORAGE_ROOT=${DATA_DIR}

# Allow direct image paths (useful for development)
MANAGER_ALLOW_IMAGE_PATHS=${MANAGER_ALLOW_IMAGE_PATHS:-true}

# Reconciler (VM health monitoring)
MANAGER_RECONCILER_DISABLED=${MANAGER_RECONCILER_DISABLED:-false}

# Optional: Host ID for self-registration
# MANAGER_HOST_ID=

# Optional: Bridge name for self-registration
MANAGER_BRIDGE=${BRIDGE_NAME:-fcbr0}

# Logging
RUST_LOG=${RUST_LOG:-info}
EOF

    sudo chmod 640 "$config_file"
    sudo chown nqrust:nqrust "$config_file"

    log_success "Manager configuration created"
}

# Generate agent configuration
generate_agent_config() {
    log_info "Generating agent configuration..."

    local config_file="${CONFIG_DIR}/agent.env"

    # Detect manager URL
    local manager_url="${MANAGER_BASE:-http://localhost:18080}"

    # If installing manager on same host, use localhost
    if [[ "${INSTALL_COMPONENTS}" == *"manager"* ]]; then
        manager_url="http://localhost:18080"
    fi

    cat <<EOF | sudo tee "$config_file" >/dev/null
# NQRust-MicroVM Agent Configuration
# Generated by installer on $(date)

# Agent bind address (listen on all interfaces)
AGENT_BIND=${AGENT_BIND:-0.0.0.0:9090}

# Advertise address - this is how the manager reaches this agent
# Using 127.0.0.1 for local-only installation (manager and agent on same machine)
AGENT_ADVERTISE_ADDR=http://127.0.0.1:9090

# Firecracker runtime directory
FC_RUN_DIR=${DATA_DIR}

# Network bridge name
FC_BRIDGE=${BRIDGE_NAME:-fcbr0}

# Manager API base URL
MANAGER_BASE=$manager_url

# Optional: Agent name (defaults to hostname)
# AGENT_NAME=\$(hostname)

# Logging
RUST_LOG=${RUST_LOG:-info}
EOF

    sudo chmod 640 "$config_file"
    sudo chown root:root "$config_file"  # Agent runs as root

    log_success "Agent configuration created"
}

# Generate UI configuration
generate_ui_config() {
    if [[ "${WITH_UI:-true}" != "true" ]]; then
        return 0
    fi

    log_info "Generating UI configuration..."

    local config_file="${CONFIG_DIR}/ui.env"

    cat <<EOF | sudo tee "$config_file" >/dev/null
# NQRust-MicroVM UI Configuration
# Generated by installer on $(date)

# API base URL
NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:18080/v1}

# WebSocket base URL
NEXT_PUBLIC_WS_BASE_URL=${NEXT_PUBLIC_WS_BASE_URL:-ws://localhost:18080}

# Brand preset (light/dark)
NEXT_PUBLIC_BRAND_PRESET=${NEXT_PUBLIC_BRAND_PRESET:-dark}

# Port
PORT=${UI_PORT:-3000}
EOF

    sudo chmod 640 "$config_file"
    sudo chown nqrust:nqrust "$config_file"

    log_success "UI configuration created"
}

# Generate unified config file (YAML)
generate_unified_config() {
    log_info "Generating unified configuration..."

    local config_file="${CONFIG_DIR}/config.yaml"

    cat <<EOF | sudo tee "$config_file" >/dev/null
# NQRust-MicroVM Configuration
# Generated by installer on $(date)

installation:
  version: "1.0.0"
  installed_at: "$(date -Iseconds)"
  install_dir: "${INSTALL_DIR}"
  data_dir: "${DATA_DIR}"
  config_dir: "${CONFIG_DIR}"

database:
  type: "${DB_TYPE:-local}"
  host: "${DB_HOST:-localhost}"
  port: ${DB_PORT:-5432}
  name: "${DB_NAME:-nexus}"
  user: "${DB_USER:-nexus}"

network:
  mode: "${NETWORK_MODE:-nat}"
  bridge_name: "${BRIDGE_NAME:-fcbr0}"
  interface: "${DETECTED_INTERFACE:-eth0}"

components:
  manager: $([ "${INSTALL_COMPONENTS}" == *"manager"* ] && echo "true" || echo "false")
  agent: $([ "${INSTALL_COMPONENTS}" == *"agent"* ] && echo "true" || echo "false")
  ui: ${WITH_UI:-true}
  container_runtime: ${WITH_CONTAINER_RUNTIME:-false}

manager:
  bind: "${MANAGER_BIND:-0.0.0.0:18080}"
  image_root: "${IMAGE_DIR}"
  storage_root: "${DATA_DIR}"

agent:
  bind: "${AGENT_BIND:-0.0.0.0:19090}"
  fc_run_dir: "${DATA_DIR}"
  fc_bridge: "${BRIDGE_NAME:-fcbr0}"
  manager_url: "${MANAGER_BASE:-http://localhost:18080}"

ui:
  port: ${UI_PORT:-3000}
  api_url: "${NEXT_PUBLIC_API_BASE_URL:-http://localhost:18080/v1}"
EOF

    sudo chmod 644 "$config_file"
    sudo chown root:root "$config_file"

    log_success "Unified configuration created"
}

# Copy helper scripts
copy_helper_scripts() {
    log_info "Copying helper scripts..."

    local scripts_src="${PROJECT_ROOT}/scripts"
    local scripts_dest="${INSTALL_DIR}/scripts"

    if [[ -d "$scripts_src" ]]; then
        # Copy useful scripts
        local helper_scripts=(
            "fc-bridge-setup.sh"
            "fc-bridge-physical.sh"
            "dev-up.sh"
        )

        for script in "${helper_scripts[@]}"; do
            if [[ -f "$scripts_src/$script" ]]; then
                sudo cp "$scripts_src/$script" "$scripts_dest/"
                sudo chmod +x "$scripts_dest/$script"
            fi
        done

        log_success "Helper scripts copied"
    else
        log_debug "No helper scripts to copy"
    fi
}

# Set final permissions
set_permissions() {
    log_info "Setting permissions..."

    # Binaries
    sudo chmod 755 "${INSTALL_DIR}/bin/"*

    # Config files (sensitive)
    sudo chmod 640 "${CONFIG_DIR}/"*.env 2>/dev/null || true

    # Data directories
    sudo chown -R nqrust:nqrust "${DATA_DIR}"
    sudo chown -R nqrust:nqrust "${IMAGE_DIR}"

    # Log directory
    sudo chown -R nqrust:nqrust "/var/log/nqrust-microvm"

    log_success "Permissions set"
}

# Show configuration summary
show_configuration_summary() {
    echo ""
    log_info "Configuration Summary:"
    echo ""
    echo "  Installation Directory: ${INSTALL_DIR}"
    echo "  Configuration Directory: ${CONFIG_DIR}"
    echo "  Data Directory: ${DATA_DIR}"
    echo "  Image Directory: ${IMAGE_DIR}"
    echo ""
    echo "  Manager API: ${MANAGER_BIND:-0.0.0.0:18080}"
    echo "  Agent API: ${AGENT_BIND:-0.0.0.0:19090}"
    if [[ "${WITH_UI:-true}" == "true" ]]; then
        echo "  UI Port: ${UI_PORT:-3000}"
    fi
    echo ""
    echo "  Network Mode: ${NETWORK_MODE:-nat}"
    echo "  Bridge: ${BRIDGE_NAME:-fcbr0}"
    echo ""
    echo "  Database: ${DB_NAME:-nexus}@${DB_HOST:-localhost}"
    echo ""
}

# Main configuration function
configure_system() {
    log_phase "8/11" "Generating Configuration"

    create_system_user
    create_directory_structure
    generate_manager_config
    generate_agent_config
    generate_ui_config
    generate_unified_config
    copy_helper_scripts
    set_permissions

    show_configuration_summary

    log_success "System configuration complete"
}

# Export functions
export -f create_system_user create_directory_structure
export -f generate_manager_config generate_agent_config generate_ui_config
export -f generate_unified_config copy_helper_scripts
export -f set_permissions show_configuration_summary
export -f configure_system
