CREATE TABLE IF NOT EXISTS vm (
id UUID PRIMARY KEY,
name TEXT NOT NULL,
state TEXT NOT NULL DEFAULT 'requested',
host_addr TEXT NOT NULL,
api_sock TEXT NOT NULL,
tap TEXT NOT NULL,
log_path TEXT NOT NULL,
http_port INT NOT NULL DEFAULT 0,
fc_unit TEXT NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS vm_event (
id BIGSERIAL PRIMARY KEY,
vm_id UUID NOT NULL REFERENCES vm(id) ON DELETE CASCADE,
at TIMESTAMPTZ NOT NULL DEFAULT now(),
level TEXT NOT NULL,
message TEXT NOT NULL
);


CREATE INDEX IF NOT EXISTS idx_vm_state ON vm(state);