ALTER TABLE snapshot ADD COLUMN IF NOT EXISTS snapshot_type TEXT NOT NULL DEFAULT 'Full';
ALTER TABLE snapshot ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES snapshot(id) ON DELETE SET NULL;
ALTER TABLE snapshot ADD COLUMN IF NOT EXISTS track_dirty_pages BOOLEAN NOT NULL DEFAULT false;

