//! Configuration file generation module.

use std::path::Path;

use anyhow::Result;

use crate::app::{InstallConfig, LogEntry};
use crate::installer::{run_command, run_sudo};

/// Generate all configuration files
pub fn generate_config(config: &InstallConfig, db_password: &str) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let config_dir = &config.config_dir;

    logs.push(LogEntry::info(format!(
        "Generating configuration in {}...",
        config_dir.display()
    )));

    // Create config directory
    let _ = run_sudo("mkdir", &["-p", &config_dir.display().to_string()]);

    // Generate manager config if needed
    if config.mode.includes_manager() {
        logs.extend(generate_manager_config(config, db_password)?);
    }

    // Generate agent config if needed
    if config.mode.includes_agent() {
        logs.extend(generate_agent_config(config)?);
    }

    // Generate UI config if needed
    if config.mode.includes_ui() {
        logs.extend(generate_ui_config(config)?);
    }

    // Generate unified YAML config
    logs.extend(generate_yaml_config(config, db_password)?);

    // Set permissions
    let _ = run_sudo("chmod", &["700", &config_dir.display().to_string()]);
    let _ = run_sudo(
        "chown",
        &["-R", "root:root", &config_dir.display().to_string()],
    );

    logs.push(LogEntry::success("Configuration generated"));

    Ok(logs)
}

/// Generate manager environment file
fn generate_manager_config(config: &InstallConfig, db_password: &str) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let db_url = format!(
        "postgresql://{}:{}@{}:{}/{}",
        config.db_user, db_password, config.db_host, config.db_port, config.db_name
    );

    // IMPORTANT: These settings are REQUIRED for proper operation (not just dev mode)
    // - ALLOW_IMAGE_PATHS=true: Required for functions/containers to work properly
    // - RECONCILER_DISABLED=1: Reconciler causes race conditions and VM creation failures
    // Only difference in dev mode is the log level
    let rust_log = if config.mode == crate::app::InstallMode::Development {
        "debug"
    } else {
        "info"
    };

    let env_content = format!(
        r#"# NQR-MicroVM Manager Configuration
# Generated by nqr-installer
# Mode: {}

# Database
DATABASE_URL={}

# Server binding
MANAGER_BIND=0.0.0.0:18080

# Storage paths
MANAGER_IMAGE_ROOT={}/images
MANAGER_STORAGE_ROOT={}/vms

# Allow direct file paths for images (REQUIRED for functions/containers)
MANAGER_ALLOW_IMAGE_PATHS=true

# Disable VM reconciler (REQUIRED - causes race conditions if enabled)
MANAGER_RECONCILER_DISABLED=1

# Host registration
MANAGER_HOST_ID=
MANAGER_BRIDGE={}

# Logging
RUST_LOG={}
"#,
        config.mode.name(),
        db_url,
        config.data_dir.display(),
        config.data_dir.display(),
        config.bridge_name,
        rust_log
    );

    let env_file = config.config_dir.join("manager.env");
    write_config_file(&env_file, &env_content)?;
    logs.push(LogEntry::success("Manager configuration generated"));

    Ok(logs)
}

/// Generate agent environment file
fn generate_agent_config(config: &InstallConfig) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    // Set debug log level for development mode
    let rust_log = if config.mode == crate::app::InstallMode::Development {
        "debug"
    } else {
        "info"
    };

    let env_content = format!(
        r#"# NQR-MicroVM Agent Configuration
# Generated by nqr-installer
# Mode: {}

# Server binding
AGENT_BIND=0.0.0.0:9090

# Firecracker runtime directory
FC_RUN_DIR={}

# Network bridge
FC_BRIDGE={}

# Manager API URL
MANAGER_BASE=http://127.0.0.1:18080

# Logging
RUST_LOG={}
"#,
        config.mode.name(),
        config.data_dir.display(),
        config.bridge_name,
        rust_log
    );

    let env_file = config.config_dir.join("agent.env");
    write_config_file(&env_file, &env_content)?;
    logs.push(LogEntry::success("Agent configuration generated"));

    Ok(logs)
}

/// Generate UI environment file
fn generate_ui_config(config: &InstallConfig) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let env_content = r#"# NQR-MicroVM UI Configuration
# Generated by nqr-installer

# API URL
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:18080/v1

# WebSocket URL
NEXT_PUBLIC_WS_BASE_URL=ws://127.0.0.1:18080

# Theme
NEXT_PUBLIC_BRAND_PRESET=dark
"#;

    let env_file = config.config_dir.join("ui.env");
    write_config_file(&env_file, env_content)?;
    logs.push(LogEntry::success("UI configuration generated"));

    Ok(logs)
}

/// Generate unified YAML configuration
fn generate_yaml_config(config: &InstallConfig, _db_password: &str) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let yaml_content = format!(
        r#"# NQR-MicroVM Configuration
# Generated by nqr-installer

installation:
  mode: {}
  install_dir: {}
  data_dir: {}
  config_dir: {}
  log_dir: {}

manager:
  bind: "0.0.0.0:18080"
  database:
    host: {}
    port: {}
    name: {}
    user: {}
    # password stored securely in manager.env
  storage:
    image_root: "{}/images"
    vm_root: "{}/vms"

agent:
  bind: "0.0.0.0:9090"
  firecracker:
    run_dir: {}
    bridge: {}
  manager_url: "http://127.0.0.1:18080"

network:
  mode: {}
  bridge: {}

ui:
  enabled: {}
  api_url: "http://127.0.0.1:18080/v1"
"#,
        config.mode.name().to_lowercase().replace(' ', "_"),
        config.install_dir.display(),
        config.data_dir.display(),
        config.config_dir.display(),
        config.log_dir.display(),
        config.db_host,
        config.db_port,
        config.db_name,
        config.db_user,
        config.data_dir.display(),
        config.data_dir.display(),
        config.data_dir.display(),
        config.bridge_name,
        config.network_mode.name().to_lowercase(),
        config.bridge_name,
        config.mode.includes_ui()
    );

    let yaml_file = config.config_dir.join("config.yaml");
    write_config_file(&yaml_file, &yaml_content)?;
    logs.push(LogEntry::success("YAML configuration generated"));

    Ok(logs)
}

/// Write a configuration file with sudo
fn write_config_file(path: &Path, content: &str) -> Result<()> {
    let cmd = format!(
        "echo '{}' | sudo tee {} > /dev/null",
        content.replace('\'', "'\"'\"'"),
        path.display()
    );
    run_command("sh", &["-c", &cmd])?;

    // Set permissions
    let _ = run_sudo("chmod", &["600", &path.display().to_string()]);

    Ok(())
}

/// Create system user for running services
pub fn create_system_user() -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    logs.push(LogEntry::info("Creating system user 'nqrust'..."));

    // Check if user exists
    let output = run_command("id", &["nqrust"]);
    if let Ok(out) = output {
        if out.status.success() {
            logs.push(LogEntry::info("User 'nqrust' already exists"));
            return Ok(logs);
        }
    }

    // Create user
    let output = run_sudo(
        "useradd",
        &[
            "--system",
            "--no-create-home",
            "--shell",
            "/usr/sbin/nologin",
            "--groups",
            "kvm",
            "nqrust",
        ],
    )?;

    if output.status.success() {
        logs.push(LogEntry::success("System user 'nqrust' created"));
    } else {
        logs.push(LogEntry::warning(
            "Failed to create user, may already exist",
        ));
    }

    Ok(logs)
}

/// Create required directories
pub fn create_directories(config: &InstallConfig) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let dirs = [
        config.install_dir.clone(),
        config.install_dir.join("bin"),
        config.data_dir.clone(),
        config.data_dir.join("vms"),
        config.data_dir.join("images"),
        config.config_dir.clone(),
        config.log_dir.clone(),
    ];

    for dir in &dirs {
        let _ = run_sudo("mkdir", &["-p", &dir.display().to_string()]);
    }

    // Set ownership for data directories
    let _ = run_sudo(
        "chown",
        &[
            "-R",
            "nqrust:nqrust",
            &config.data_dir.display().to_string(),
        ],
    );

    logs.push(LogEntry::success("Directories created"));

    Ok(logs)
}
