"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import type { BackendKind } from "@/lib/types";
import { useCreateStorageBackend, useScanNfsExports, useScanIscsiTargets } from "@/lib/queries";

interface Field {
  key: string;
  label: string;
  placeholder?: string;
  hint?: string;
  type?: "text" | "password";
}

/** Per-kind config fields. Keep aligned with `apps/manager/src/features/storage/config.rs::validate`. */
const KIND_CONFIG: Record<BackendKind, { label: string; description: string; fields: Field[] }> = {
  local_file: {
    label: "Local file",
    description: "VM disks live as files on the manager's local filesystem. No external dependencies.",
    fields: [
      {
        key: "root_dir",
        label: "Root directory",
        placeholder: "/srv/fc/vms",
        hint: "Directory where the manager creates VM disk files. Must be writable by the manager process.",
      },
    ],
  },
  nfs: {
    label: "NFS",
    description:
      "VM disks live as files on an NFS export. The manager auto-mounts the share under /var/lib/nqrust/nfs/ — operators don't run mount.nfs. Agents mount on demand on their own hosts.",
    fields: [
      {
        key: "server",
        label: "NFS server",
        placeholder: "10.0.0.5",
        hint: "IP or hostname of the NFS server.",
      },
      {
        key: "export",
        label: "Export path",
        placeholder: "/mnt/tank/vms",
        hint: "Path the server exports.",
      },
      {
        key: "mount_base",
        label: "Mount base (optional)",
        placeholder: "/var/lib/nqrust/nfs",
        hint: "Where the manager creates per-(server, export) mount points. Default /var/lib/nqrust/nfs. Most operators leave this blank.",
      },
    ],
  },
  iscsi: {
    label: "iSCSI (generic)",
    description:
      "Operator-managed iSCSI target. Provisioning is no-op — LUNs are pre-created on the target and registered via API.",
    fields: [
      {
        key: "target_iqn",
        label: "Target IQN",
        placeholder: "iqn.2024-01.com.example:storage",
        hint: "iSCSI Qualified Name of the target.",
      },
      {
        key: "portal",
        label: "Portal (optional)",
        placeholder: "10.0.0.5:3260",
        hint: "Discovery portal — used by the agent for iscsiadm login.",
      },
    ],
  },
  truenas_iscsi: {
    label: "TrueNAS (iSCSI)",
    description:
      "TrueNAS REST API provisions one zvol + extent + target per VM disk (Harvester-CSI style). The full IQN is generated by TrueNAS from its global basename — operators don't pick an IQN.",
    fields: [
      {
        key: "endpoint",
        label: "TrueNAS endpoint",
        placeholder: "https://truenas.lan",
        hint: "Base URL of the TrueNAS REST API.",
      },
      {
        key: "api_key_env",
        label: "API key env var name",
        placeholder: "TRUENAS_API_KEY",
        hint: "Name of the environment variable on the manager process that holds the API key. Don't paste the key itself here.",
      },
      { key: "pool", label: "Pool", placeholder: "NQRust", hint: "ZFS pool that hosts the per-volume zvols." },
      {
        key: "target_name_prefix",
        label: "Target name prefix (optional)",
        placeholder: "nqrust-v-",
        hint: "Each VM disk creates a target named <prefix><uuid>. Default 'nqrust-v-'. The full IQN is <truenas-basename>:<prefix><uuid>.",
      },
      {
        key: "portal_group_id",
        label: "Portal group id (optional)",
        placeholder: "1",
        hint: "TrueNAS portal group id to associate each new target with. Without this, the operator must add a portal group to each new target via the TrueNAS UI before clients can connect.",
      },
      {
        key: "initiator_group_id",
        label: "Initiator group id (optional)",
        placeholder: "1",
        hint: "TrueNAS initiator group id. Same role as the portal group — set it to make provisioning fully hands-off.",
      },
      {
        key: "portal",
        label: "Discovery portal (optional)",
        placeholder: "10.0.0.5:3260",
        hint: "If unset, the agent uses iscsiadm discovery to find a portal.",
      },
    ],
  },
  spdk_lvol: {
    label: "SPDK lvol",
    description: "Single-node SPDK lvol backend. Requires SPDK running locally.",
    fields: [
      {
        key: "rpc_socket",
        label: "RPC socket",
        placeholder: "/var/tmp/spdk.sock",
        hint: "SPDK JSON-RPC Unix socket path.",
      },
      { key: "lvs_name", label: "LVS name", placeholder: "lvs0", hint: "Name of the SPDK logical volume store." },
    ],
  },
};

const KINDS: BackendKind[] = ["local_file", "nfs", "iscsi", "truenas_iscsi", "spdk_lvol"];

function NfsExportField({
  server,
  value,
  onChange,
}: {
  server: string;
  value: string;
  onChange: (v: string) => void;
}) {
  const enabled = server.trim().length > 0;
  const { data, isFetching, error } = useScanNfsExports(server, enabled);
  const exports = data?.exports ?? [];

  if (!enabled || (exports.length === 0 && !isFetching && !error)) {
    return (
      <Input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="/mnt/tank/vms"
      />
    );
  }
  if (isFetching && exports.length === 0) {
    return (
      <Input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={`Scanning ${server}…`}
      />
    );
  }
  if (error || exports.length === 0) {
    return (
      <div className="space-y-1.5">
        <Input
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="/mnt/tank/vms"
        />
        <p className="text-xs text-amber-600">
          Could not list exports from {server} — type the path manually.
        </p>
      </div>
    );
  }
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger>
        <SelectValue placeholder="Pick an export" />
      </SelectTrigger>
      <SelectContent>
        {exports.map((e) => (
          <SelectItem key={e.path} value={e.path}>
            {e.path}
            {e.allowed && (
              <span className="ml-2 text-xs text-muted-foreground">→ {e.allowed}</span>
            )}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function IscsiTargetDiscovery({ portal }: { portal: string }) {
  const [open, setOpen] = useState(false);
  const enabled = open && portal.trim().length > 0;
  const { data, isFetching, error } = useScanIscsiTargets(portal, enabled);

  if (!portal.trim()) {
    return null;
  }
  return (
    <div className="text-xs">
      <button
        type="button"
        className="text-blue-600 hover:underline"
        onClick={() => setOpen((v) => !v)}
      >
        {open ? "Hide" : "Show"} reachable targets
      </button>
      {open && (
        <div className="mt-2 rounded-md border bg-muted/50 p-2">
          {isFetching && <p className="text-muted-foreground">Scanning {portal}…</p>}
          {error && (
            <p className="text-amber-600">Could not reach {portal} via iscsiadm.</p>
          )}
          {data?.targets.length === 0 && !isFetching && (
            <p className="text-muted-foreground">No targets returned by {portal}.</p>
          )}
          {data?.targets && data.targets.length > 0 && (
            <ul className="space-y-1 font-mono text-xs">
              {data.targets.map((t, i) => (
                <li key={`${t.portal}-${t.iqn}-${i}`}>
                  <span className="text-muted-foreground">{t.portal}</span> {t.iqn}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}

export function BackendCreateDialog({ open, onOpenChange }: Props) {
  const create = useCreateStorageBackend();
  const [name, setName] = useState("");
  const [kind, setKind] = useState<BackendKind>("nfs");
  const [isDefault, setIsDefault] = useState(false);
  const [config, setConfig] = useState<Record<string, string>>({});

  const spec = KIND_CONFIG[kind];

  function reset() {
    setName("");
    setKind("nfs");
    setIsDefault(false);
    setConfig({});
  }

  async function submit() {
    const cleaned: Record<string, unknown> = {};
    // Numeric config fields the manager expects as integers, not
    // strings. Coerce here since `<Input>` always returns strings.
    const NUMERIC_KEYS = new Set(["portal_group_id", "initiator_group_id"]);
    for (const f of spec.fields) {
      const v = (config[f.key] ?? "").trim();
      if (!v && !/(optional)/i.test(f.label)) {
        // Server-side validate() will reject; surface a friendlier first
        // pass here by skipping submit until required fields are filled.
        return;
      }
      if (v) {
        if (NUMERIC_KEYS.has(f.key)) {
          const n = Number(v);
          if (Number.isFinite(n) && Number.isInteger(n)) {
            cleaned[f.key] = n;
          }
          // Non-numeric input on a numeric field is silently dropped
          // here — server-side validation will surface the missing
          // field if the operator typed something invalid.
        } else {
          cleaned[f.key] = v;
        }
      }
    }
    await create.mutateAsync({
      name: name.trim(),
      kind,
      is_default: isDefault,
      config: cleaned as Record<string, unknown>,
    });
    if (!create.isError) {
      reset();
      onOpenChange(false);
    }
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        onOpenChange(o);
        if (!o) reset();
      }}
    >
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Add storage backend</DialogTitle>
          <DialogDescription>
            Configure a place where VM disks can live. External backends (NFS, iSCSI, TrueNAS) need
            the network/credentials below.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="bk-name">Name</Label>
            <Input
              id="bk-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. truenas-prod"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="bk-kind">Kind</Label>
            <Select value={kind} onValueChange={(v) => { setKind(v as BackendKind); setConfig({}); }}>
              <SelectTrigger id="bk-kind">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {KINDS.map((k) => (
                  <SelectItem key={k} value={k}>
                    {KIND_CONFIG[k].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">{spec.description}</p>
          </div>

          {spec.fields.map((f) => (
            <div key={f.key} className="space-y-1.5">
              <Label htmlFor={`bk-cfg-${f.key}`}>{f.label}</Label>
              {kind === "nfs" && f.key === "export" ? (
                <NfsExportField
                  server={String(config["server"] ?? "")}
                  value={String(config[f.key] ?? "")}
                  onChange={(v) => setConfig({ ...config, [f.key]: v })}
                />
              ) : (kind === "iscsi" || kind === "truenas_iscsi") && f.key === "portal" ? (
                <>
                  <Input
                    id={`bk-cfg-${f.key}`}
                    type="text"
                    value={String(config[f.key] ?? "")}
                    onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
                    placeholder={f.placeholder}
                  />
                  <IscsiTargetDiscovery portal={String(config[f.key] ?? "")} />
                </>
              ) : (
                <Input
                  id={`bk-cfg-${f.key}`}
                  type={f.type ?? "text"}
                  value={String(config[f.key] ?? "")}
                  onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
                  placeholder={f.placeholder}
                />
              )}
              {f.hint && <p className="text-xs text-muted-foreground">{f.hint}</p>}
            </div>
          ))}

          <div className="flex items-center justify-between rounded-md border p-3">
            <div className="space-y-0.5">
              <Label htmlFor="bk-default" className="cursor-pointer">
                Set as default
              </Label>
              <p className="text-xs text-muted-foreground">
                New VMs use the default backend when none is selected.
              </p>
            </div>
            <Switch id="bk-default" checked={isDefault} onCheckedChange={setIsDefault} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={create.isPending}>
            Cancel
          </Button>
          <Button onClick={submit} disabled={!name.trim() || create.isPending}>
            {create.isPending ? "Adding..." : "Add backend"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
