"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import type { BackendKind } from "@/lib/types";
import { useCreateStorageBackend, useScanNfsExports, useScanIscsiTargets } from "@/lib/queries";
import { LvmInitializeDialog } from "@/components/storage/lvm-initialize-dialog";

interface Field {
  key: string;
  label: string;
  placeholder?: string;
  hint?: string;
  type?: "text" | "password" | "boolean";
  /** Hide the field until another field has a value. Used so the
   *  Export Path doesn't render before the operator has typed an NFS
   *  server (there's nothing to pick from). */
  requiresField?: string;
  /** Tuck the field behind the "Show advanced options" toggle. The
   *  manager has sane defaults for every advanced field; operators only
   *  see them after explicitly opening the disclosure. */
  advanced?: boolean;
}

/** Per-kind config fields. Keep aligned with `apps/manager/src/features/storage/config.rs::validate`. */
const KIND_CONFIG: Record<BackendKind, { label: string; description: string; fields: Field[] }> = {
  local_file: {
    label: "Local file",
    description: "VM disks live as files on the manager's local filesystem. No external dependencies.",
    fields: [
      {
        key: "root_dir",
        label: "Root directory",
        placeholder: "/srv/fc/vms",
        hint: "Directory where the manager creates VM disk files. Must be writable by the manager process.",
      },
    ],
  },
  nfs: {
    label: "NFS",
    description:
      "VM disks live as files on an NFS export. The manager auto-mounts the share under /var/lib/nqrust/nfs/ — operators don't run mount.nfs. Agents mount on demand on their own hosts.",
    fields: [
      {
        key: "server",
        label: "NFS server",
        placeholder: "10.0.0.5",
        hint: "IP or hostname of the NFS server.",
      },
      {
        key: "export",
        label: "Export path",
        placeholder: "/mnt/tank/vms",
        hint: "Path the server exports.",
        requiresField: "server",
      },
      {
        key: "mount_base",
        label: "Mount base",
        placeholder: "/var/lib/nqrust/nfs",
        hint: "Where the manager creates per-(server, export) mount points. Default /var/lib/nqrust/nfs.",
        advanced: true,
      },
    ],
  },
  iscsi: {
    label: "iSCSI (generic)",
    description:
      "Operator-managed iSCSI target. Provisioning is no-op — LUNs are pre-created on the target and registered via API.",
    fields: [
      {
        key: "target_iqn",
        label: "Target IQN",
        placeholder: "iqn.2024-01.com.example:storage",
        hint: "iSCSI Qualified Name of the target.",
      },
      {
        key: "portal",
        label: "Portal",
        placeholder: "10.0.0.5:3260",
        hint: "Discovery portal — used by the agent for iscsiadm login.",
        advanced: true,
      },
    ],
  },
  truenas_iscsi: {
    label: "TrueNAS (iSCSI)",
    description:
      "TrueNAS REST API provisions one zvol + extent + target per VM disk (Harvester-CSI style). The full IQN is generated by TrueNAS from its global basename — operators don't pick an IQN.",
    fields: [
      {
        key: "endpoint",
        label: "TrueNAS endpoint",
        placeholder: "https://truenas.lan",
        hint: "Base URL of the TrueNAS REST API.",
      },
      {
        key: "api_key_env",
        label: "API key env var name",
        placeholder: "TRUENAS_API_KEY",
        hint: "Name of the environment variable on the manager process that holds the API key. Don't paste the key itself here.",
      },
      { key: "pool", label: "Pool", placeholder: "NQRust", hint: "ZFS pool that hosts the per-volume zvols." },
      {
        key: "target_name_prefix",
        label: "Target name prefix",
        placeholder: "nqrust-v-",
        hint: "Each VM disk creates a target named <prefix><uuid>. Default 'nqrust-v-'.",
        advanced: true,
      },
      {
        key: "portal_group_id",
        label: "Portal group id",
        placeholder: "auto-discover or auto-create",
        hint: "TrueNAS portal group id. The manager auto-discovers existing groups and falls back to auto-creating one if none exist. Override only if you need a specific group.",
        advanced: true,
      },
      {
        key: "initiator_group_id",
        label: "Initiator group id",
        placeholder: "auto-discover or auto-create",
        hint: "TrueNAS initiator group id. Same auto-discover behavior as portal group.",
        advanced: true,
      },
      {
        key: "portal",
        label: "Discovery portal",
        placeholder: "10.0.0.5:3260",
        hint: "If unset, the agent uses iscsiadm discovery to find a portal.",
        advanced: true,
      },
    ],
  },
  spdk_lvol: {
    label: "SPDK lvol",
    description: "Single-node SPDK lvol backend. Requires SPDK running locally.",
    fields: [
      {
        key: "rpc_socket",
        label: "RPC socket",
        placeholder: "/var/tmp/spdk.sock",
        hint: "SPDK JSON-RPC Unix socket path.",
      },
      { key: "lvs_name", label: "LVS name", placeholder: "lvs0", hint: "Name of the SPDK logical volume store." },
    ],
  },
  iscsi_lvm: {
    label: "iSCSI + LVM (vendor-agnostic)",
    description:
      "Vendor-agnostic shared storage: one iSCSI LUN holds an LVM volume group, one LV per VM disk. Works against any iSCSI target (TrueNAS, ZFS, Pure, NetApp). Requires a one-time Volume Group initialization after creation.",
    fields: [
      {
        key: "portal",
        label: "iSCSI Portal (host:port)",
        placeholder: "192.168.1.10:3260",
        hint: "Discovery portal — host:port of the iSCSI target.",
      },
      {
        key: "iqn",
        label: "Target IQN",
        placeholder: "iqn.2005-10.org.freenas.ctl:vmstore",
        hint: "iSCSI Qualified Name of the target that holds the shared LUN.",
      },
      {
        key: "vg_name",
        label: "Volume Group Name",
        placeholder: "vg-nqrust",
        hint: "LVM volume group name. Created during the one-time initialize step.",
      },
      {
        key: "lun",
        label: "LUN",
        placeholder: "0",
        hint: "LUN number on the target. Defaults to 0.",
        advanced: true,
      },
      {
        key: "saferemove",
        label: "Zero-out LV on delete (slower but secure)",
        type: "boolean",
        hint: "When enabled, dd zeroes the LV before lvremove. Slower but prevents data leakage between VMs.",
        advanced: true,
      },
    ],
  },
};

// Recommended kinds shown by default in the dropdown. Covers the three
// mainstream paths: single-host file, NAS, vendor-agnostic SAN.
const BASIC_KINDS: BackendKind[] = ["local_file", "nfs", "iscsi_lvm"];

// Advanced kinds — vendor-specific or operationally heavyweight. Hidden
// behind a "Show advanced kinds" disclosure to keep the default UX simple
// without removing capability:
//   - iscsi (generic): pre-cut LUN passthrough, 1 VM per LUN. iscsi_lvm
//     covers ~95% of this case with auto-provisioning.
//   - truenas_iscsi: TrueNAS REST adapter for native ZFS snapshots / thin
//     provisioning. Power-user mode for shops that want ZFS features.
//   - spdk_lvol: NVMe vhost-user direct. Requires hugepages, vhost socket
//     plumbing, kernel modules. High-throughput / clustering future.
const ADVANCED_KINDS: BackendKind[] = ["iscsi", "truenas_iscsi", "spdk_lvol"];

function NfsExportField({
  server,
  value,
  onChange,
}: {
  server: string;
  value: string;
  onChange: (v: string) => void;
}) {
  const enabled = server.trim().length > 0;
  const { data, isFetching, error } = useScanNfsExports(server, enabled);
  const exports = data?.exports ?? [];

  if (!enabled || (exports.length === 0 && !isFetching && !error)) {
    return (
      <Input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="/mnt/tank/vms"
      />
    );
  }
  if (isFetching && exports.length === 0) {
    return (
      <Input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={`Scanning ${server}…`}
      />
    );
  }
  if (error || exports.length === 0) {
    return (
      <div className="space-y-1.5">
        <Input
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="/mnt/tank/vms"
        />
        <p className="text-xs text-amber-600">
          Could not list exports from {server} — type the path manually.
        </p>
      </div>
    );
  }
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger>
        <SelectValue placeholder="Pick an export" />
      </SelectTrigger>
      <SelectContent>
        {exports.map((e) => (
          <SelectItem key={e.path} value={e.path}>
            {e.path}
            {e.allowed && (
              <span className="ml-2 text-xs text-muted-foreground">→ {e.allowed}</span>
            )}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function IscsiTargetDiscovery({ portal }: { portal: string }) {
  const [open, setOpen] = useState(false);
  const enabled = open && portal.trim().length > 0;
  const { data, isFetching, error } = useScanIscsiTargets(portal, enabled);

  if (!portal.trim()) {
    return null;
  }
  return (
    <div className="text-xs">
      <button
        type="button"
        className="text-blue-600 hover:underline"
        onClick={() => setOpen((v) => !v)}
      >
        {open ? "Hide" : "Show"} reachable targets
      </button>
      {open && (
        <div className="mt-2 rounded-md border bg-muted/50 p-2">
          {isFetching && <p className="text-muted-foreground">Scanning {portal}…</p>}
          {error && (
            <p className="text-amber-600">Could not reach {portal} via iscsiadm.</p>
          )}
          {data?.targets.length === 0 && !isFetching && (
            <p className="text-muted-foreground">No targets returned by {portal}.</p>
          )}
          {data?.targets && data.targets.length > 0 && (
            <ul className="space-y-1 font-mono text-xs">
              {data.targets.map((t, i) => (
                <li key={`${t.portal}-${t.iqn}-${i}`}>
                  <span className="text-muted-foreground">{t.portal}</span> {t.iqn}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}

/** Render a single config field. Extracted so the basic and advanced
 *  passes share the same rendering logic — including the iSCSI portal
 *  discovery helper and boolean switches. */
function renderField(
  f: Field,
  kind: BackendKind,
  config: Record<string, string | boolean>,
  setConfig: (c: Record<string, string | boolean>) => void,
) {
  if (f.type === "boolean") {
    const checked = config[f.key] === true;
    return (
      <div
        key={f.key}
        className="flex items-center justify-between rounded-md border p-3"
      >
        <div className="space-y-0.5">
          <Label htmlFor={`bk-cfg-${f.key}`} className="cursor-pointer">
            {f.label}
          </Label>
          {f.hint && <p className="text-xs text-muted-foreground">{f.hint}</p>}
        </div>
        <Switch
          id={`bk-cfg-${f.key}`}
          checked={checked}
          onCheckedChange={(v) => setConfig({ ...config, [f.key]: v })}
        />
      </div>
    );
  }
  const strVal = typeof config[f.key] === "string" ? (config[f.key] as string) : "";
  return (
    <div key={f.key} className="space-y-1.5">
      <Label htmlFor={`bk-cfg-${f.key}`}>{f.label}</Label>
      {kind === "nfs" && f.key === "export" ? (
        <NfsExportField
          server={String(config["server"] ?? "")}
          value={strVal}
          onChange={(v) => setConfig({ ...config, [f.key]: v })}
        />
      ) : (kind === "iscsi" || kind === "truenas_iscsi" || kind === "iscsi_lvm") &&
        f.key === "portal" ? (
        <>
          <Input
            id={`bk-cfg-${f.key}`}
            type="text"
            value={strVal}
            onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
            placeholder={f.placeholder}
          />
          <IscsiTargetDiscovery portal={strVal} />
        </>
      ) : (
        <Input
          id={`bk-cfg-${f.key}`}
          type={f.type === "password" ? "password" : "text"}
          value={strVal}
          onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
          placeholder={f.placeholder}
        />
      )}
      {f.hint && <p className="text-xs text-muted-foreground">{f.hint}</p>}
    </div>
  );
}

export function BackendCreateDialog({ open, onOpenChange }: Props) {
  const create = useCreateStorageBackend();
  const [name, setName] = useState("");
  const [kind, setKind] = useState<BackendKind>("local_file");
  const [isDefault, setIsDefault] = useState(false);
  const [config, setConfig] = useState<Record<string, string | boolean>>({});
  const [showAdvanced, setShowAdvanced] = useState(false);
  // Tier the kind dropdown: BASIC_KINDS (local_file, nfs, iscsi_lvm) shown
  // by default, ADVANCED_KINDS (iscsi generic, truenas_iscsi, spdk_lvol)
  // revealed via a toggle below the Select. Auto-on if the currently-
  // selected kind is one of the advanced ones — keeps the form sane when
  // the operator edits a row that already used an advanced kind.
  const [showAdvancedKinds, setShowAdvancedKinds] = useState(false);
  // After a successful create of an iscsi_lvm backend the operator must
  // run the one-time `vgcreate` against the freshly-attached LUN. We
  // surface that as a transient post-create banner inside the same
  // dialog so the next step is impossible to miss. Task 15 wires the
  // actual destructive-confirmation dialog; for now the CTA is a
  // placeholder that logs.
  const [postCreate, setPostCreate] = useState<
    { kind: BackendKind; backendName: string; backendId: string } | null
  >(null);
  const [initOpen, setInitOpen] = useState(false);

  const spec = KIND_CONFIG[kind];
  const basicFields = spec.fields.filter((f) => !f.advanced);
  const advancedFields = spec.fields.filter((f) => f.advanced);

  function reset() {
    setName("");
    setKind("local_file");
    setIsDefault(false);
    setConfig({});
    setShowAdvanced(false);
  }

  async function submit() {
    const cleaned: Record<string, unknown> = {};
    // Numeric config fields the manager expects as integers, not
    // strings. Coerce here since `<Input>` always returns strings.
    const NUMERIC_KEYS = new Set(["portal_group_id", "initiator_group_id", "lun"]);
    for (const f of spec.fields) {
      const raw = config[f.key];
      // Booleans are stored natively in `config`; everything else is a
      // string from <Input>. Treat them separately so we don't trim()
      // a boolean.
      if (f.type === "boolean") {
        if (typeof raw === "boolean") {
          cleaned[f.key] = raw;
        }
        continue;
      }
      const v = (typeof raw === "string" ? raw : "").trim();
      // A field is optional when it's tucked behind the Advanced
      // toggle (operators don't have to set it — the manager has
      // sane defaults), or when its label still says "(optional)"
      // for backward compat with legacy specs that haven't been
      // migrated to the `advanced` flag.
      const isOptional = f.advanced || /(optional)/i.test(f.label);
      // Hidden fields (requiresField unmet) are never required —
      // they don't render, so the operator has no way to fill them.
      const isHidden =
        f.requiresField !== undefined &&
        !String(config[f.requiresField] ?? "").trim();
      if (!v && !isOptional && !isHidden) {
        // Server-side validate() will reject; surface a friendlier first
        // pass here by skipping submit until required fields are filled.
        return;
      }
      if (v) {
        if (NUMERIC_KEYS.has(f.key)) {
          const n = parseInt(v, 10);
          if (Number.isFinite(n)) {
            cleaned[f.key] = n;
          }
          // Non-numeric input on a numeric field is silently dropped
          // here — server-side validation will surface the missing
          // field if the operator typed something invalid.
        } else {
          cleaned[f.key] = v;
        }
      }
    }
    const submittedName = name.trim();
    const submittedKind = kind;
    const created = await create.mutateAsync({
      name: submittedName,
      kind,
      is_default: isDefault,
      config: cleaned as Record<string, unknown>,
    });
    if (!create.isError) {
      if (submittedKind === "iscsi_lvm") {
        // Don't close the dialog yet — keep the operator here so the
        // post-create CTA is unmissable. Reset the form so the banner
        // is visually distinct from the input fields.
        reset();
        setPostCreate({
          kind: submittedKind,
          backendName: submittedName,
          backendId: created.id,
        });
      } else {
        reset();
        onOpenChange(false);
      }
    }
  }

  return (
    <>
    <Dialog
      open={open}
      onOpenChange={(o) => {
        onOpenChange(o);
        if (!o) {
          reset();
          setPostCreate(null);
        }
      }}
    >
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Add storage backend</DialogTitle>
          <DialogDescription>
            Configure a place where VM disks can live. External backends (NFS, iSCSI, TrueNAS) need
            the network/credentials below.
          </DialogDescription>
        </DialogHeader>

        {postCreate && postCreate.kind === "iscsi_lvm" && (
          <div className="space-y-3 rounded-md border border-amber-300 bg-amber-50 p-4 dark:border-amber-700 dark:bg-amber-950/40">
            <div className="space-y-1">
              <p className="text-sm font-medium">
                Backend <span className="font-mono">{postCreate.backendName}</span> added.
              </p>
              <p className="text-xs text-muted-foreground">
                Initialize the LVM volume group on the shared LUN before VMs can use this
                backend. This is destructive — anything already on the LUN will be erased.
              </p>
            </div>
            <div className="flex gap-2">
              <Button size="sm" onClick={() => setInitOpen(true)}>
                Initialize Volume Group
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  setPostCreate(null);
                  onOpenChange(false);
                }}
              >
                Skip for now
              </Button>
            </div>
          </div>
        )}

        {!postCreate && (
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label htmlFor="bk-name">Name</Label>
              <Input
                id="bk-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. truenas-prod"
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="bk-kind">Kind</Label>
              <Select value={kind} onValueChange={(v) => { setKind(v as BackendKind); setConfig({}); }}>
                <SelectTrigger id="bk-kind">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {BASIC_KINDS.map((k) => (
                    <SelectItem key={k} value={k}>
                      {KIND_CONFIG[k].label}
                    </SelectItem>
                  ))}
                  {(showAdvancedKinds || ADVANCED_KINDS.includes(kind)) &&
                    ADVANCED_KINDS.map((k) => (
                      <SelectItem key={k} value={k}>
                        {KIND_CONFIG[k].label}
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs text-muted-foreground flex-1">{spec.description}</p>
                {!ADVANCED_KINDS.includes(kind) && (
                  <button
                    type="button"
                    onClick={() => setShowAdvancedKinds((v) => !v)}
                    className="text-xs text-primary hover:underline whitespace-nowrap"
                  >
                    {showAdvancedKinds
                      ? "Hide advanced kinds"
                      : `Show advanced kinds (${ADVANCED_KINDS.length})`}
                  </button>
                )}
              </div>
            </div>

            {basicFields.map((f) => {
              // Hide fields that depend on another field until that
              // dependency has a value. Lets us drop the Export Path
              // input until the operator types an NFS server.
              if (
                f.requiresField &&
                !String(config[f.requiresField] ?? "").trim()
              ) {
                return null;
              }
              return renderField(f, kind, config, setConfig);
            })}

            {advancedFields.length > 0 && (
              <div className="space-y-3">
                <button
                  type="button"
                  className="text-xs text-blue-600 hover:underline"
                  onClick={() => setShowAdvanced((v) => !v)}
                >
                  {showAdvanced ? "Hide" : "Show"} advanced options ({advancedFields.length})
                </button>
                {showAdvanced &&
                  advancedFields.map((f) => renderField(f, kind, config, setConfig))}
              </div>
            )}

            <div className="flex items-center justify-between rounded-md border p-3">
              <div className="space-y-0.5">
                <Label htmlFor="bk-default" className="cursor-pointer">
                  Set as default
                </Label>
                <p className="text-xs text-muted-foreground">
                  New VMs use the default backend when none is selected.
                </p>
              </div>
              <Switch id="bk-default" checked={isDefault} onCheckedChange={setIsDefault} />
            </div>
          </div>
        )}

        {!postCreate && (
          <DialogFooter>
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={create.isPending}>
              Cancel
            </Button>
            <Button onClick={submit} disabled={!name.trim() || create.isPending}>
              {create.isPending ? "Adding..." : "Add backend"}
            </Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
    <LvmInitializeDialog
      backendId={postCreate?.backendId ?? null}
      backendName={postCreate?.backendName ?? ""}
      open={initOpen}
      onOpenChange={(o) => {
        setInitOpen(o);
        // After the operator has run (or skipped) the initialize step
        // dismiss the create dialog along with its post-create banner.
        if (!o && postCreate) {
          setPostCreate(null);
          onOpenChange(false);
        }
      }}
    />
    </>
  );
}
