#!/bin/bash
# Setup script for NQRust-MicroVM docs server on Biznet Gio VM
# Run this script once on your VM to set up Caddy and prepare for deployments
#
# Usage: sudo ./setup-docs-server.sh [your-domain-or-ip]
# Example with IP: sudo ./setup-docs-server.sh 103.123.45.67
# Example with domain: sudo ./setup-docs-server.sh docs.example.com

set -e

DOCS_DIR="/var/www/docs"
DEPLOY_USER="${DEPLOY_USER:-deploy}"
SERVER_ADDRESS="${1:-:80}"

echo "=== NQRust-MicroVM Docs Server Setup ==="
echo "Server address: $SERVER_ADDRESS"
echo "Docs directory: $DOCS_DIR"
echo "Deploy user: $DEPLOY_USER"
echo ""

# Detect OS
if [ -f /etc/debian_version ]; then
    OS="debian"
elif [ -f /etc/redhat-release ]; then
    OS="rhel"
else
    echo "Unsupported OS. Please install Caddy manually."
    exit 1
fi

# Install Caddy
echo "=== Installing Caddy ==="
if [ "$OS" = "debian" ]; then
    apt-get update
    apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
    apt-get update
    apt-get install -y caddy
else
    dnf install -y 'dnf-command(copr)'
    dnf copr enable -y @caddy/caddy
    dnf install -y caddy
fi

# Create deploy user if it doesn't exist
echo "=== Setting up deploy user ==="
if ! id "$DEPLOY_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$DEPLOY_USER"
    echo "Created user: $DEPLOY_USER"
fi

# Create docs directory
echo "=== Creating docs directory ==="
mkdir -p "$DOCS_DIR"
chown -R "$DEPLOY_USER:$DEPLOY_USER" "$DOCS_DIR"
chmod 755 "$DOCS_DIR"

# Create placeholder index.html
cat > "$DOCS_DIR/index.html" << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>NQRust-MicroVM Docs</title>
    <style>
        body { font-family: system-ui, sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: #1a1a2e; color: #eee; }
        .container { text-align: center; }
        h1 { color: #f97316; }
    </style>
</head>
<body>
    <div class="container">
        <h1>NQRust-MicroVM Documentation</h1>
        <p>Deployment pending. Push to the main branch to deploy docs.</p>
    </div>
</body>
</html>
EOF
chown "$DEPLOY_USER:$DEPLOY_USER" "$DOCS_DIR/index.html"

# Setup SSH key for deploy user
echo "=== Setting up SSH for deploy user ==="
DEPLOY_SSH_DIR="/home/$DEPLOY_USER/.ssh"
mkdir -p "$DEPLOY_SSH_DIR"
touch "$DEPLOY_SSH_DIR/authorized_keys"
chmod 700 "$DEPLOY_SSH_DIR"
chmod 600 "$DEPLOY_SSH_DIR/authorized_keys"
chown -R "$DEPLOY_USER:$DEPLOY_USER" "$DEPLOY_SSH_DIR"

# Configure Caddy
echo "=== Configuring Caddy ==="
cat > /etc/caddy/Caddyfile << EOF
# NQRust-MicroVM Documentation Server
# Generated by setup-docs-server.sh

$SERVER_ADDRESS {
    root * $DOCS_DIR
    file_server

    # Enable gzip compression
    encode gzip

    # SPA fallback for Hugo
    try_files {path} {path}/ /index.html

    # Cache static assets
    @static {
        path *.css *.js *.png *.jpg *.jpeg *.gif *.ico *.svg *.woff *.woff2
    }
    header @static Cache-Control "public, max-age=31536000"

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
    }

    # Handle 404
    handle_errors {
        respond "{err.status_code} {err.status_text}"
    }
}
EOF

# Enable and start Caddy
echo "=== Starting Caddy ==="
systemctl enable caddy
systemctl restart caddy

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo ""
echo "1. Generate an SSH key pair for GitHub Actions deployment:"
echo "   ssh-keygen -t ed25519 -f github_deploy_key -N ''"
echo ""
echo "2. Add the public key to the deploy user's authorized_keys:"
echo "   cat github_deploy_key.pub >> /home/$DEPLOY_USER/.ssh/authorized_keys"
echo ""
echo "3. Add these secrets to your GitHub repository (Settings > Secrets > Actions):"
echo "   - VM_HOST: Your VM's IP address or hostname"
echo "   - VM_USER: $DEPLOY_USER"
echo "   - VM_SSH_KEY: Contents of github_deploy_key (private key)"
echo "   - VM_SSH_PORT: 22 (or your custom port)"
echo "   - DOCS_BASE_URL: http://$SERVER_ADDRESS/ (or https:// if using domain)"
echo ""
echo "4. Test the connection:"
echo "   ssh -i github_deploy_key $DEPLOY_USER@your-vm-ip"
echo ""
echo "5. Push changes to docs/ folder to trigger deployment"
echo ""
echo "Your docs will be available at: http://$SERVER_ADDRESS/"
